### ISSUE TITLE
请问下 这个软件有IPA格式的文件吗？

### ISSUE THREAD

**Issue by Initializist** [superk589/PrincessGuide#4]
大佬您好， 我从NGA过来的。 我在NGA使用您提供的网站后发现 Test Flight 没有测试位置了。 我想问下您能不能提供一下IPA格式的文件？我想尝试用Cydia Impactor 或者 Altstore安装到我的iPhone， 谢谢！

**Comment by superk589** [comment]
@Initializist 
稍后我会提供一个ipa 放在release里面

**Comment by Initializist** [comment]
感激不尽！！！

**Comment by superk589** [comment]
@Initializist 已经上传了
https://github.com/superk589/PrincessGuide/releases/tag/1.1.4-r161

**Comment by Initializist** [comment]
非常感谢！

**Comment by Initializist** [comment]
不好意思，我刚刚尝试装了app，发现app一直闪退。 我用的是iPhone 10， IOS 13.5. 您需要我提供什么crash log吗？

**Comment by superk589** [comment]
@Initializist 确实会闪退 我确认下问题 然后重新发一个

**Comment by Initializist** [comment]
@superk589 非常感谢！麻烦您了！

**Comment by superk589** [comment]
@Initializist 打包方式有问题 现在已经重新上传 请再次尝试下

**Comment by Initializist** [comment]
好的，谢谢！
