### ISSUE TITLE
Podfile内的引用的Pod版本为什么不写死呢？

### ISSUE THREAD

**Issue by Jack--Ma** [superk589/PrincessGuide#6]
clone工程后想debug看下代码，pod install后发现和.lock内的版本差别巨大，然后看到Podfile内没有指定版本，这里还是指定一下比较好，否则无法保证我们和你的依赖环境一致...直接导致打开工程后编译报错，修复编译问题后各种Crash...😂😂

pod install 后的版本diff：
<img width="664" alt="WX20200615-155905@2x" src="https://user-images.githubusercontent.com/10970854/84632402-6e727d80-af21-11ea-87d7-e6a78c9ba02e.png">

Podfile 文件：
<img width="867" alt="WX20200615-160231@2x" src="https://user-images.githubusercontent.com/10970854/84632548-a5e12a00-af21-11ea-8944-00ca82f49e6b.png">

**Comment by superk589** [comment]
master 分支上无需执行 pod install 因为 Pods/ 目录并没有放到 .gitignore 中
另外不写死是因为这是个较新而且较小的项目，使用的依赖也基本都是最新版，如果依赖更新了我也希望能使用 pod update 快速更新

**Comment by Jack--Ma** [comment]
感觉可以把依赖加一下，即便不显示指定版本，用~>指定一个小版本也比较好，一般项目追求稳定，不需要Pod实时依赖最新的版本，求稳定版本就行。

**Comment by Jack--Ma** [comment]
感觉可以把依赖加一下，即便不显示指定版本，用~>指定一个小版本也比较好。

**Comment by Jack--Ma** [comment]
好吧，我是考虑如果后续有人给你提PR，涉及到Pod的升级或者降级，会有点麻烦，每次都使用Pod Update更新最新版...按理说不应该保持使用一个稳定版本吗😂

**Comment by superk589** [comment]
这个问题其实不存在的，因为根据 [CocoaPods 的官方建议](http://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control)
我选择将 Pods/ 纳入版本库管理，这样的好处是每次 Clone 之后，直接就可以运行，这样做可以最大限度的降低一般人员的参与难度（比如一些人只想翻译文本，本身不是开发者也不知道 CocoaPods）

**Comment by Jack--Ma** [comment]
呃，有道理，看来是我好久没用Github了...在公司我们都是隐藏Pods目录的，Podfile依赖写死，禁止使用Pod Update命令...😂
